[repository]
name = "windows-pointer-linux"
authors = ["junaga"]
commit_pins = [
    ["a0136d8c04687bb36eb8a28eb9d1ff92aea99704", "d8b5e601cabe4b23fb92ec7d726a3ea4f734828a"],
]

[windows-pointer-linux]
description = "the windows 11 pointer algorithm, except it escaped"
authors = ["junaga"]
output = "build/windows-pointer-linux.so"
build = [
    "cmake -S . -B build -DBUILD_TESTING=OFF",
    "cmake --build build --parallel",
]
