[repository]
name = "windows-pointer-linux"
authors = ["windows-pointer-linux contributors"]

[windows-pointer-linux]
description = "the windows 11 pointer algorithm, except it escaped"
authors = ["windows-pointer-linux contributors"]
output = "build/windows-pointer-linux.so"
build = [
    "cmake -S . -B build -DBUILD_TESTING=OFF",
    "cmake --build build --parallel",
]

